
# tap repositories and their packages

tap homebrew/core
brew abseil
brew aom
brew apr
brew apr-util
brew argon2
brew aribb24
brew assimp
brew autoconf
brew boost
brew bpytop
brew brew-gem
brew brotli
brew c-ares
brew ca-certificates
brew cairo
brew certifi
brew chezmoi
brew cjson
brew cmake
brew cmake-docs
brew curl
brew dav1d
brew dbus
brew double-conversion
brew duti
brew ffmpeg
brew flac
brew fmt
brew fontconfig
brew freetds
brew freetype
brew frei0r
brew fribidi
brew fzf
brew gd
brew gettext
brew gh
brew ghostscript
brew giflib
brew git
brew git-gui
brew glib
brew gmp
brew gnu-sed
brew gnupg
brew gnutls
brew go
brew graphite2
brew handbrake
brew harfbuzz
brew highway
brew hunspell
brew icu4c@76
brew icu4c@77
brew imath
brew jasper
brew jbig2dec
brew jpeg-turbo
brew jpeg-xl
brew krb5
brew lame
brew leptonica
brew libarchive
brew libass
brew libassuan
brew libavif
brew libb2
brew libbluray
brew libdeflate
brew libebml
brew libevent
brew libgcrypt
brew libgpg-error
brew libidn
brew libidn2
brew libksba
brew libmatroska
brew libmicrohttpd
brew libmng
brew libnghttp2
brew libogg
brew libplacebo
brew libpng
brew libpq
brew librist
brew libsamplerate
brew libsndfile
brew libsodium
brew libsoxr
brew libssh
brew libssh2
brew libtasn1
brew libtiff
brew libtool
brew libunibreak
brew libunistring
brew libusb
brew libuv
brew libvidstab
brew libvmaf
brew libvorbis
brew libvpx
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew libyaml
brew libzip
brew liquidprompt
brew little-cms2
brew localtunnel
brew lsd
brew luajit
brew lux
brew lz4
brew lzo
brew m4
brew mbedtls
brew md4c
brew mkvdts2ac3
brew mkvtoolnix
brew molten-vk
brew mpdecimal
brew mpg123
brew mpv
brew mujs
brew mysql
brew mysql@8.4
brew net-snmp
brew nettle
brew nlohmann-json
brew node
brew npth
brew oh-my-posh
brew oniguruma
brew opencore-amr
brew openexr
brew openjpeg
brew openldap
brew openssl@3
brew opus
brew osx-cpu-temp
brew p11-kit
brew pandoc
brew pango
brew pcre2
brew php
brew pinentry
brew pinentry-mac
brew pixman
brew pkgconf
brew protobuf@29
brew pugixml
brew pyenv
brew python@3.12
brew python@3.13
brew qt
brew rav1e
brew rbenv
brew readline
brew ripmime
brew rtmpdump
brew rubberband
brew ruby
brew ruby-build
brew sdl2
brew shaderc
brew snappy
brew speex
brew sqlite
brew srt
brew svt-av1
brew tcl-tk@8
brew tesseract
brew theora
brew tidy-html5
brew tldr
brew tree
brew uchardet
brew unbound
brew unixodbc
brew utf8cpp
brew vapoursynth
brew vulkan-headers
brew vulkan-loader
brew webp
brew wget
brew woff2
brew x264
brew x265
brew xorgproto
brew xvid
brew xz
brew yarn
brew yt-dlp
brew zeromq
brew zimg
brew zlib
brew zoxide
brew zstd

tap homebrew/cask
cask 1password-cli
cask 86box
cask alfred
cask deltachat
cask devtoys
cask docker
cask filebot
cask floorp
cask font-hack-nerd-font
cask freecad
cask iina
cask jdownloader
cask mactex
cask obs
cask obsidian
cask qbittorrent
cask qlmarkdown
cask quarto
cask rar
cask signal
cask vlc

tap homebrew/services

tap jandedobbeleer/oh-my-posh

tap rcmdnk/file
brew brew-file

# Other Homebrew packages
brew gem-colorls

# App Store applications
appstore 1569813296 1Password for Safari (2.27.1)
appstore 1616822987 Affinity Photo 2 (2.5.4)
appstore 918858936 Airmail (5.7.7)
appstore 404009241 BBEdit (15.1.2)
appstore 6740447481 BiLangPage Pro (1.12)
appstore 0 ColorSlurp (4.0.0)
appstore 1035236694 Commander One (3.9)
appstore 640199958 Developer (10.6.5)
appstore 450113817 DEVONagent (3.11.8)
appstore 1580323719 EdgeView (4.7.9)
appstore 939343785 Icon Set Creator (1.1.13)
appstore 1501296766 Icon Set Studio (1.1.14)
appstore 1413833786 Kiano (2.2)
appstore 557428110 LightBlue (5.1.6)
appstore 872698314 MoneyMoney (2.4.39)
appstore 1064959555 NewFileMenu (1.7.4)
appstore 1094255754 Outbank (3.14.4)
appstore 967805235 Paste (4.4.2)
appstore 418818452 PhotoSync (4.2)
appstore 1497435571 Simple Comic (1.9.8)
appstore 1006087419 SnippetsLab (2.4.2)
appstore 1303140142 SomaFM miniplayer (1.2.0)
appstore 449155338 SomaFM (1.2.15)
appstore 1246969117 Steam Link (1.3.10)
appstore 747648890 Telegram (11.6)
appstore 406825478 Telephone (1.6)
appstore 899247664 TestFlight (3.5.2)
appstore 655390161 TowerMadness 2 (2.0)
appstore 1436522307 Transmit (5.10.8)
appstore 623795237 Ulysses (2.8.3)
appstore 1531249804 Uni Detector (1.2.1)
appstore 966486618 WeatherPro (1.2.2)
appstore 1668083311 Whisper Transcription (9.9)
appstore 497799835 Xcode (15.4)
appstore 457622435 Yoink (3.6.98)
appstore 6450893458 智谱清言 (1.0.33)
